### ISSUE TITLE
Add "Connect with Paypal"-Button to Piggymetrics View

### ISSUE THREAD

**Issue by bajo1207** [bajo1207/piggymetrics#5] opened 2019-12-13 21:51 UTC
Create a button in the UI that enables the user to log in with.
https://developer.paypal.com/docs/connect-with-paypal/

**Comment by jblossey** [comment] 2019-12-23 18:21
**Please also think about #16 when adressing this issue.**

**Comment by jblossey** [comment] 2019-12-28 23:18
Button callable (see PR #22 ). Yet to include html into piggymetrics view.

**Comment by jblossey** [comment] 2019-12-30 21:34
Duplicate of newer issue #26

**Comment by jblossey** [comment] 2020-01-10 15:59
This issue is worked on on branch [sign-in-button](https://github.com/bajo1207/piggymetrics/tree/joachimbachemathiesen/ch26/sign-in-button). Although as single application the gateway now displays the Paypal button. When launched with all other services it still only displays the text (at least on my local build).

**Comment by AndreasSpateneder** [comment] 2020-01-12 16:47
Login button is now visible and completely integrated into the login page.

**Closed as completed by AndreasSpateneder** 2020-01-12 16:47 UTC
Labels: bug, duplicate, enhancement, help wanted
